### ISSUE TITLE
Remove or force login

### ISSUE THREAD

**Issue by dreammaker** [Voxel8/OctoPrint-V8theme#1]
The fact that some things are hidden or don't function until you login to OctoPrint is extremely confusing.  Today, I tried to print and spent a few minutes wondering why dragging/dropping a file wasn't working.  The UI gave no feedback or indication why it wasn't working.  Most web apps that have logged-in-only functionality redirect you to a page with just a login form, so it's clear you must login before proceeding.  When there is both logged-in and logged-out functionality on a page, when you try to interact with the stuff that requires you to login, the logged-in-only stuff is visible as it always is, and the UI prompts you to log in when you click it.  This isn't just to increase conversion; it actually improves usability.

So I propose to either remove the login completely or force users to login in order to do or see anything at all.  I would say that forced-login is the way, except I just remembered that the printer UI is always exposed without any login, so maybe that's the way to go.

**Comment by Lucky1313** [comment]
Octoprint checks the config file for whether to enable login. We can fully disable it easily by manually turning off access control in the config. It is also possible to autologin users that exist on a certain network (i.e. localhost or a 192.168 network)

**Comment by jminardi** [comment]
Maybe we should just disable login on the local network?

On Thu, Aug 27, 2015 at 11:39 AM, David Hedin notifications@github.com
wrote:

> Octoprint checks the config file for whether to enable login. We can fully
> disable it easily by manually turning off access control in the config. It
> is also possible to autologin users that exist on a certain network (i.e.
> localhost or a 192.168 network)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Voxel8/OctoPrint-V8theme/issues/1#issuecomment-135472096
> .

## 

Jack Minardi
jack.minardi.org
jack@minardi.org

**Comment by Lucky1313** [comment]
We should be able to auto-login on the local network, although that might break if someone has a poorly set up network (not using standard private network range). For auto-login to work though, it has to be set to log in as a specific user. Would we create the user, or should this be something the client does? If the client sets up the user, I don't know if there is a way to automatically apply these settings after the user is created.
