### ISSUE TITLE
Seconds Precision? 

### ISSUE THREAD

**Issue by eroneill** [Voxel8/OctoPrint-V8theme#20]
When a print finishes it displays the print time down to 16 decimals on the seconds.  This seems to be way too precise to be useful.

 @kevingelion ?

**Comment by weedgrease** [comment]
Where does it display it like this? In the top left corner? A screenshot would be lovely

**Comment by eroneill** [comment]
![image](https://cloud.githubusercontent.com/assets/12863209/18176027/e218ec74-7041-11e6-861c-85d49156b8ab.png)
 Its the Chrome notification - this is what it says

**Comment by weedgrease** [comment]
Ah, cool. Good catch thanks!
